.UL ON
.OP
.LM 1
.RM 68
.MT 5
.MB 5
.RM 72
.PL 70
.OJ OFF
.TC Tacowaa	#
                        Ta‰cowaàa
.TC Ryba	#
Ryba
.TC z	#
z
.TC rakiem	#
††††††rakiem
.TC ryba	#
††††††rybaz rakiem

1.††††A
††††††a.†††Pietruszka
†††††††††††i.†††Z
†††††††††††ii††.Pasternakiem
†††††††††††iii.†Z
†††††††††††iv††.Pasternakiem
††††††b†††.A
2††††.Cebula
3††††.Z czosnkom





a                        
dziewczyna




z
kozakom






.CW 10
.CW 8
     JAPAN†††††††††ESE:   COULD NOT PROVIDE, WP LANGUAGE PACK  
     ARABIC:††††††††††††††††                                                       

     CYRYLIC:†††††††††††††††  ,   ,   ,   ,   ,   ,   ,   

     POLISH:††††††††††††††††§•, ®©, ùà, èÜ, Ωæ