 WS2000 1.00     PRINTER            188 
 0  0
i0 0i^  6^_  6_[
K                                                              
K$).38=                                      [a66a\10\]10]b11be0eg1gE  0   0   0    0    0E&%PAGE&
E  0   0   2    8  432Ev[
K$).38=BGLQV[`ejoty~ГИНТЧ  
L$).38=BGLQV[`ejoty~ГИНТЧ  [[
L$).38=BGLQV[`ejoty~ГИНТЧ  
I$).38=BGLQV[`ejoty~ГИНТЧ  [[
I$).38=BGLQV[`ejoty~ГИНТЧ  
I$).38<AFKPUZ_dinsx|БЖЛР  [ TaфcowaИa 
 Ryba 
 z 
 rakiem 
 ryba 
z rakiem

1.A
a.Pietruszka
i.Z
ii.Pasternakiem
iii.Z
iv.Pasternakiem
b.A
2.Cebula
3.Z czosnkom





a	
dziewczyna




z
kozakom



[
I$).38<AFKPUZ_dinsx|БЖЛР  
I$).38<AFKPUZ_dinsx|БЖЛР  [


	JAPANESE:   COULD NOT PROVIDE, WP LANGUAGE PACK  

	ARABIC:                                                       

	CYRYLIC:  ,   ,   ,   ,   ,   ,   ,   

	POLISH:де, ий, ЭИ, ПЖ, ╜╛