.PO 9
.MT 5
.MB 5
.PL 70
                      Ta‰cowaàa
Ryba
z
††††††rakiem
††††††ryba
z rakiem

1.††††A
††††††a.†††Pietruszka
†††††††††††i.†††Z
†††††††††††ii††.Pasternakiem
†††††††††††iii.†Z
†††††††††††iv.††Pasternakiem
††††††b.†††A
2††††.Cebula
3††††.Z czosnkom





a                          
dziewczyna




z
kozakom






.CW 10
.CW 8
     JAPAN†††††††††ESE:   COULD NOT PROVIDE, WP LANGUAGE PACK  
     ARABIC:††††††††††††††††                                                       

     CYRYLIC:†††††††††††††††  ,   ,   ,   ,   ,   ,   ,   

     POLISH:††††††††††††††††§•, ®©, ùà, èÜ, Ωæ